Fine-grained reproduce flags and testing (#204)
* Added test model for ... testing. Has minimal requirements and means
tests can be independent of model driver implementation. A platonic
ideal if you will.

* Added config options for fine-grained reproduce options. Input, exe
and restart reproduce can be turned on independently of each other.

* Added extensive testing of init/setup and reproduce.

* Added new test to travis, and pytest dependency.

* Added pytest to setup.py

* Moved PBS env init to cli to remove dependence on PBS for setup

* Add coverage to pytest

* Updated travis badge URL

* Cast run_id to string before subscripting

* Fixed old API call in profile command

* Fixed old f90nml API call in mitgcm model

* Rolled back change to os.makedirs. Removed exist_ok argument as it
isn't python2 compliant. Just use local mkdir_p function.

* Initialise existing_files attribute to empty set so no need to
check if the attribute exists. Avoids spurious pylint errors.

* Refactored try/except block in run_userscript. Avoids spurious pylint
error about CalledProcessError not having errno attribute, but also
cleaner to separate into different except blocks.

* Disabled E1136 check for routine in mom driver (not really used anyway)

* Add pylint check to travis

* Added pylint to travis requirements

* Added scipy dependency, and scipy for travis

* Wrapped input manifest load in try/except block to
make more error resistant

* Added cd context to payu_setup wrapper for cleaner code

* Added more tests to exe and input reproduce to clarify logic
for corner cases

* Added setuptools as a build requirement after conda error with CircleCI:

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.

* Change to conda update --all

* Added tests for scaninputs

* Commented out PBS torque setup as not used, doesn't install
correctly and sometimes throws random errors when the source
can't be found.

* Added back in payu_test.py to tests. Added path to payu_test as invoking from 
pytest from root dir

* Added coveralls badge to README

* Added sweep to payu setup in tests to reduce boilerplate code