Added setuptools as a build requirement after conda error with CircleCI:
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.